[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.12.0"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap-index.xml"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/#prendre-contact"
  status = 301

[[redirects]]
  from = "/contact/"
  to = "/#prendre-contact"
  status = 301
